name: CD-Liara

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Liara 
      url: https://mobinkaram.liara.run
    concurrency:
      group: liara-deploy
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Install Liara CLI
        run: npm i -g @liara/cli@7
      - name: Deploy
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          # or your PAT secret
          GITHUB_CONTENT_TOKEN: ${{ secrets.GITHUB_CONTENT_TOKEN }}
          CONTENT_REPO_OWNER: ${{ secrets.CONTENT_REPO_OWNER }}
          CONTENT_REPO_NAME: ${{ secrets.CONTENT_REPO_NAME }}
          CONTENT_REPO_BRANCH: ${{ secrets.CONTENT_REPO_BRANCH }}
          CONTENT_ENGINEER_OWNER: ${{ secrets.CONTENT_ENGINEER_OWNER }}
          CONTENT_ENGINEER_REPO: ${{ secrets.CONTENT_ENGINEER_REPO }}
          CONTENT_ENGINEER_BRANCH: ${{ secrets.CONTENT_ENGINEER_BRANCH }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
        run: |
          liara deploy --app="mobinkaram" --api-token="$LIARA_TOKEN" --no-app-logs --port=3000 --platform=node --build-location=iran
